import { Mails } from "lucide-react";
import { FC } from "react";

export const Footer: FC = () => {
  return (
    <div className="text-center flex flex-col items-center text-xs text-zinc-700 gap-1">
      <div className="text-zinc-400">
        Answer generated by large language models, plz double check for
        correctness.
      </div>
      <div className="text-zinc-400">
        LLM, Vector DB powered by the Lepton AI and OpenAI api.
      </div>

      <div className="flex items-center justify-center flex-wrap gap-x-4 gap-y-2 mt-2 text-zinc-400">
        <a className="hover:text-zinc-950" href="https://mulanai.com/">
          Home
        </a>
        <a
          className="hover:text-zinc-950"
          href="https://search.mulanai.com"
        >
          API Playground
        </a>
        <a
          className="hover:text-zinc-950"
          href="https://github.com/shibing624/SmartSearch"
        >
          Python Library
        </a>
        <a className="hover:text-zinc-950" href="https://twitter.com/OilandLuca">
          Twitter
        </a>
        <a className="hover:text-zinc-950" href="https://blog.csdn.net/mingzai624">
          Blog
        </a>
      </div>
    </div>
  );
};
